{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaleway-k8s-node-coffee.fullname" . }}
  labels:
    {{- include "scaleway-k8s-node-coffee.labels" . | nindent 4 }}
type: Opaque
data:
  SCW_ACCESS_KEY: {{  required "A valid .Values.secrets.accessKey entry required!" .Values.secrets.accessKey | b64enc | quote }}
  SCW_SECRET_KEY: {{  required "A valid .Values.secrets.secretKey entry required!" .Values.secrets.secretKey | b64enc | quote }}
  SCW_DEFAULT_ZONE: {{  required "A valid .Values.secrets.defaultZone entry required!" .Values.secrets.defaultZone | b64enc | quote }}
  SCW_DEFAULT_REGION: {{  required "A valid .Values.secrets.defaultRegion entry required!" .Values.secrets.defaultRegion | b64enc | quote }}
{{- end }}
