apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleway-k8s-node-coffee.serviceAccountName" . }}
  labels:
    {{- include "scaleway-k8s-node-coffee.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
