name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Highest tag
        id: highestTag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo ::set-output name=highest::$(git tag | grep -E "^v?([0-9]+\.)+[0-9]+$" | sort -r -V | head -n1)
      - name: Enable experimental on dockerd
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get tag
        uses: olegtarasov/get-tag@v1
        id: tagName
      - name: Make release
        run: make release
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          IMAGE_TAG: ${{ steps.tagName.outputs.tag }}

  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: getversion
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/4.2.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Change appVersion
        run:  yq e -i '.appVersion="${{ steps.getversion.outputs.tag }}"' charts/scaleway-k8s-node-coffee/Chart.yaml
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
